name: Java CI with Maven (PR)

on:
  pull_request:
    types: [ opened ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: avides/actions-project-version-check@latest
      id: actions_project_version_check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-to-check: pom.xml
    - name: use-version-from-check
      run: echo "New version is: " ${{ steps.actions_project_version_check.outputs.version }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
